### ISSUE TITLE
can we convert depth map to real world metrics ?

### ISSUE THREAD

**Issue by imneonizer** [bolianchen/pytorch_depth_from_videos_in_the_wild#2]
I want to find how far a vehicle is from the camera in meters

**Comment by bolianchen** [comment]
Hi Imneonizer

The depth net predicts scale-less depth maps. Therefore, you need to obtain the scale factor by one-time calibration at the beginning. For example, you need to know the actual depths in meters of several points in some image samples, and calculate the mean of actual_depths/predicted_depths as the scale factor.

Best,
Bolian
