### ISSUE TITLE
what instrinsic parameters are being used ?

### ISSUE THREAD

**Issue by imneonizer** [bolianchen/pytorch_depth_from_videos_in_the_wild#3]
The readme says write intrinsic parameters to a file:
````
1344.8 0.0 640.0 0.0 1344.8 360.0 0.0 0.0 1.0
````

Can you please share what information each number refers to?

**Comment by bolianchen** [comment]
they are (fx, s, u0, 0.0, fy, v0, 0.0, 0.0, 1.0)
fx, fy: focal lengths
u0, v0: principal point
s: skew coefficient
